//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmd.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cmd.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes:.
        /// </summary>
        internal static string AttributesSection {
            get {
                return ResourceManager.GetString("AttributesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert value of argument &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string CanNotParseArgumentValueException {
            get {
                return ResourceManager.GetString("CanNotParseArgumentValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command was canceled..
        /// </summary>
        internal static string CommandCanceledException {
            get {
                return ResourceManager.GetString("CommandCanceledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed with unexpected error..
        /// </summary>
        internal static string CommandExecutionException {
            get {
                return ResourceManager.GetString("CommandExecutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string CommandsSection {
            get {
                return ResourceManager.GetString("CommandsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string ExamplesSection {
            get {
                return ResourceManager.GetString("ExamplesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not execute this command outside command execution scope..
        /// </summary>
        internal static string NoCommandContextExecutionScope {
            get {
                return ResourceManager.GetString("NoCommandContextExecutionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not execute this command because command context is not current in execution scope..
        /// </summary>
        internal static string NotCurrentCommandContextException {
            get {
                return ResourceManager.GetString("NotCurrentCommandContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; does not have a default value..
        /// </summary>
        internal static string RequiredArgumentException {
            get {
                return ResourceManager.GetString("RequiredArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax:.
        /// </summary>
        internal static string SyntaxSection {
            get {
                return ResourceManager.GetString("SyntaxSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many values specified fot argument &apos;{0}&apos;..
        /// </summary>
        internal static string TooManyValuesForArgumentException {
            get {
                return ResourceManager.GetString("TooManyValuesForArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not recognized as an argument of &apos;{1}&apos; command..
        /// </summary>
        internal static string UnknownArgumentException {
            get {
                return ResourceManager.GetString("UnknownArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not recognized as a command..
        /// </summary>
        internal static string UnknownCommandException {
            get {
                return ResourceManager.GetString("UnknownCommandException", resourceCulture);
            }
        }
    }
}
